language: python

python:
  - "3.6"

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

if:
  - tag IS blank

before_install:
  - sudo apt-get update -q
  - sudo apt-get install libsodium-dev -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - poetry install -v

script:
  - poetry run pytest tests/
#  - poetry run pytest examples/

before_deploy:
  - make docs
  - poetry config http-basic.pypi __token__ $PYPI_TOKEN
  - poetry build
  - export VERSION=$(cat pyproject.toml | awk '$1 ~ /^version/ {print $3}' | sed 's/"//g')
  - export TAG=${VERSION%.*}
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git tag $TAG -f
  - git push https://${GH_TOKEN}@github.com/baking-bad/pytezos.git $TAG -f

deploy:
  - provider: script
    script: poetry publish
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    local_dir: docs/build
    github_token: $GH_TOKEN
    on:
      branch: master
