version: "3.8"
services:
  notebook:
    build:
      context: .
      dockerfile: michelson-kernel.dockerfile
    ports:
      - 8888:8888

  sandbox_node:
    image: bakingbad/sandboxed-node:v20.3-1
    ports:
      - 8732:8732
