name: Release notifications
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Libsodium
      run: sudo apt-get update -q && sudo apt-get install libsodium-dev -y
    - name: Install
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.6.0
        poetry_version: 1.0
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.6.0
        poetry_version: 1.0
        args: poetry run pytest tests/
    - name: telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Pytezos ${{ env.RELEASE_VERSION }} has been released 🎉
          More info at https://github.com/baking-bad/pytezos/releases/tag/${{ env.RELEASE_VERSION }}
    - name: slack notification
      uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: |
          Pytezos ${{ env.RELEASE_VERSION }} has been released 🎉
          More info at https://github.com/baking-bad/pytezos/releases/tag/${{ env.RELEASE_VERSION }}
