name: Release notifications
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6.x'
    - name: Install dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install libsodium-dev libsecp256k1-dev libgmp-dev -y
        curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        poetry install -v
    - name: Run tests
      run: poetry run pytest tests/
    - name: telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Pytezos ${{ env.RELEASE_VERSION }} has been released 🎉
          More info at https://github.com/baking-bad/pytezos/releases/tag/${{ env.RELEASE_VERSION }}
    - name: slack notification
      uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: |
          Pytezos ${{ env.RELEASE_VERSION }} has been released 🎉
          More info at https://github.com/baking-bad/pytezos/releases/tag/${{ env.RELEASE_VERSION }}
