name: Notify
on:
  push:
    tags:
      - '*.*.0'

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@master
    - name: telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Pytezos ${{ github.ref_name }} has been released 🎉
          More info at https://github.com/baking-bad/pytezos/releases/tag/${{ github.ref_name }}
    - name: slack notification
      uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: |
          Pytezos ${{ github.ref_name }} has been released 🎉
          More info at https://github.com/baking-bad/pytezos/releases/tag/${{ github.ref_name }}
