name: Notify
on:
  push:
    # FIXME: Temporary
    # tags:
    #   - '*.*.0'
    branches:
      - ci/release-notifications

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@master
    - name: telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        # FIXME: Temporary
        message: |
          Pytezos 3.12.0 has been released 🎉
          More info at https://github.com/baking-bad/pytezos/releases/tag/3.12.0
    - name: slack notification
      uses: Ilshidur/action-slack@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        # FIXME: Temporary
        args: |
          Pytezos 3.12.0 has been released 🎉
          More info at https://github.com/baking-bad/pytezos/releases/tag/3.12.0
