name: Release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@master
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v2.1.4
    - name: Install dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install libsodium-dev libsecp256k1-dev libgmp-dev -y
    - name: Install project
      run: make install
    - name: Poetry publish
      run: |
        poetry config http-basic.pypi __token__ ${{secrets.PYPI_TOKEN}}
        poetry build
        poetry publish
    - name: Build github release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
