name: Tests
on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            python-version: [
              '3.8',
              '3.9',
            ]
          - os: macos-latest
            arch: arm64
            python-version: [
              '3.10',
            ]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v2.1.4
    - name: Install binary dependencies
      run: make install-deps
    - name: Install project dependencies
      run: make install
    - name: Run lint
      run: make lint
    - name: Run tests
      run: make test
    - name: Make docs
      if: github.ref == 'refs/heads/master'
      run: poetry run make docs
    - name: Deploy to GH Pages
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
